before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/containerscrew/tftools/cmd.version={{ .Tag }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: 'tftools'
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
nfpms:
  - id: tftools
    package_name: tftools
    file_name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    homepage: https://github.com/containerscrew/tftools
    vendor: Containerscrew
    description: Easy CLI with useful terraform/terragrunt tools
    maintainer: Containerscrew <info@containerscrew.com>
    license: Apache 2.0 license
    formats:
      - apk
      - deb
      - rpm
      - archlinux
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
signs:
  - artifacts: all
    cmd: gpg2
    signature: "${artifact}_sig"
    output: true # for testing
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    # Stdin data to be given to the signature command as stdin.
    #
    # Templates: allowed
#    stdin: '{{ .Env.GPG_PASSWORD }}'
#
#    # StdinFile file to be given to the signature command as stdin.
#    stdin_file: ./.password
snapshot:
  name_template: "{{ .Tag }}"
release:
  draft: false
changelog:
  sort: asc
  skip: false
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# homebrew package
brews:
  - # GitHub repository to push the formula
    tap:
      owner: containerscrew
      name: tftools
    name: tftools
    url_template: "https://github.com/containerscrew/tftools/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: https://github.com/containerscrew/tftools
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: Formula
    description: "Easy CLI with useful terraform/terragrunt tools"
    license: "Apache 2.0 license"
