# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftools < Formula
  desc "Easy CLI with useful terraform/terragrunt tools"
  homepage "https://github.com/containerscrew/tftools"
  version "0.6.1"
  license "Apache 2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containerscrew/tftools/releases/download/v0.6.1/tftools-darwin-arm64.tar.gz"
      sha256 "c88acd1a54f824af3bd007231dfe0e30fe90e266b37df4258408692fc50bdcf2"

      def install
        bin.install "tftools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/tftools/releases/download/v0.6.1/tftools-darwin-amd64.tar.gz"
      sha256 "f4885816bc9e91c6cefddcad21974c38ad0fc33b88309d87151df16d6df72f66"

      def install
        bin.install "tftools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/tftools/releases/download/v0.6.1/tftools-linux-arm64.tar.gz"
      sha256 "cea5b2b7a064827c0923ed0244e8eb46d75366880bc566175cf71d0f31321800"

      def install
        bin.install "tftools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/tftools/releases/download/v0.6.1/tftools-linux-amd64.tar.gz"
      sha256 "374732def980d1614ba3daf6e76c1cf6a9065afe929eef75dabaa99a27acaacf"

      def install
        bin.install "tftools"
      end
    end
  end
end
