# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftools < Formula
  desc "Easy CLI with useful terraform/terragrunt tools"
  homepage "https://github.com/containerscrew/tftools"
  version "0.5.0"
  license "Apache 2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containerscrew/tftools/releases/download/v0.5.0/tftools-darwin-arm64.tar.gz"
      sha256 "3c97d56ee456ffa50976f1bf64c557a816e78a45805fdf538b06110cf188ef46"

      def install
        bin.install "tftools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/tftools/releases/download/v0.5.0/tftools-darwin-amd64.tar.gz"
      sha256 "1cfd09da1248cc72d162269246fd3202c6078eae8831fdf4414489a033622a07"

      def install
        bin.install "tftools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/tftools/releases/download/v0.5.0/tftools-linux-amd64.tar.gz"
      sha256 "dbceb1ac7a8dd7a0c8198f64478f96c4eb179b43fc7c59999268d68fc676f3a3"

      def install
        bin.install "tftools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/tftools/releases/download/v0.5.0/tftools-linux-arm64.tar.gz"
      sha256 "10b9348ae29063a6082225d94b765b177b18a5837869d905105abae13a3abe9e"

      def install
        bin.install "tftools"
      end
    end
  end
end
