# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftools < Formula
  desc "Easy CLI with useful terraform/terragrunt tools"
  homepage "https://github.com/containerscrew/tftools"
  version "0.7.0"
  license "Apache 2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containerscrew/tftools/releases/download/v0.7.0/tftools-darwin-arm64.tar.gz"
      sha256 "04e4c1d321c5f3894c7e0aca77d7092be735268d699fe9ba159e7d651d7240a3"

      def install
        bin.install "tftools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/tftools/releases/download/v0.7.0/tftools-darwin-amd64.tar.gz"
      sha256 "ffd5291beb06dd8a396ee88bea38b95a8e165f3c3a0b8102325643ac78c89f8a"

      def install
        bin.install "tftools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/tftools/releases/download/v0.7.0/tftools-linux-arm64.tar.gz"
      sha256 "9f90cda1b929265d5663e147f4fc634957d11f17b96312774460882cd89f39af"

      def install
        bin.install "tftools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/tftools/releases/download/v0.7.0/tftools-linux-amd64.tar.gz"
      sha256 "ab2dbf8d5f05dbf602c2aeb90483bbdaf2fdd968d850ea57a9b669635187d810"

      def install
        bin.install "tftools"
      end
    end
  end
end
